### ISSUE TITLE
Multiple SN populations

### ISSUE THREAD

**Issue by kbarbary** [kbarbary/snpgm#1]
Discuss.

cc @MichelleLochner @kponder

**Comment by drphilmarshall** [comment]
Good place to start could be getting out Kara's talk slides and turning the equations into a PGM, on the white board (and then later, daft). Then, we hack the importance sampling script to work on the new model. Could we re-do the importance sampling inference on the test dataset we already have, but with the new 2-component model? We should see that only one component is needed!

**Comment by kbarbary** [comment]
We started by updating the dataset simulation to have more SNe: 200 SNe with 50 SNe at low-z (0.02-0.1) and 150 SNe at high- (0.5-0.6) and reran with the current model:
![globalsamples](https://cloud.githubusercontent.com/assets/970135/6089682/79db8b88-ae1b-11e4-8daf-89b9e37c7a63.png)

(There's a problem with how we did the "intrinsic scatter" in this version.)

**Comment by kponder** [comment]
We discussed how multiple populations of SNeIa will affect the previous PGM and generated a new one to reflect the changes.

We added the ability to generate a mock SNeIa dataset from two different populations. We then modified the likelihood to be able to create a plot like above but with extra parameters to account for the two populations. 

The first set of processing is still running so we were unable to produce a similar plot.

![snpgm_multipop](https://cloud.githubusercontent.com/assets/9933624/6089690/a392f010-ae1b-11e4-8dd2-c626844ce478.png)

**Comment by kponder** [comment]
Here is the result from running 200 supernovae with two populations.

![globalsamples](https://cloud.githubusercontent.com/assets/9933624/6094843/52478e28-aef2-11e4-9a75-c6532136377d.png)

**Comment by kbarbary** [comment]
Very cool!

**Comment by MichelleLochner** [comment]
Well done both of you!! Have you tried running the original code (single population) on the multiple population dataset? You should see a bias and can start investigating how much of a second population you need (and with what parameters) to start inducing a bias in the cosmology.

**Comment by kbarbary** [comment]
@MichelleLochner that would be cool. Topic for another issue though, so I'm closing this one as done!
