### ISSUE TITLE
Math needs writing down

### ISSUE THREAD

**Issue by drphilmarshall** [kbarbary/snpgm#4]
@kbarbary in lieu of this, can you check in suitable whiteboard images please? Then, I am imagining a single latex document that sets out our stall, and then has one section for each model we implement. This document can then be copied and pasted from when we come to write papers - but in the meantime it can serve to explain which models we are investigating (and why).

**Comment by kbarbary** [comment]
@rbiswas4 just said that he'll write some math down. Latex is fine, eventually we should put some of it in a RST document for inclusion in sphinx docs.

**Comment by rbiswas4** [comment]
I put down some of the math describing the model of the first hack. There are a couple of things that I still want to add aside from references to equations, but more importantly, I am worried about not having a good consistent notation. Anyway, I might not be working on this a lot in the very next few days so it is a good time to get other comments on this. This is currently in https://github.com/rbiswas4/snpgm/tree/master/doc. Let me know if you want a PR, or want to copy things over etc.

**Comment by kponder** [comment]
Thanks @rbiswas4 ! Can you please check in `preamble.tex`(and any other required files) so that the document compiles? Thanks!

**Comment by rbiswas4** [comment]
@kponder Sorry about that. Not sure if this is the best way to go for the future or I should just expand out stuff like \be in the document itself. Anyway, we can think about this later, I added the required files necessary for compilation. I typically keep these files in the tex/latex directory under `kpsewhich --expand-path='$TEXMFHOME'`, but they will work if they are in the local directory as well.

Would be good if someone reads this and gets back to me about parts that have mistakes/are not understandable.

**Comment by kponder** [comment]
Thanks @rbiswas4. I uncommented `\input{preamble}` at the beginning as well and it compiles correctly.

**Comment by drphilmarshall** [comment]
Moving all math discussion to #10!
